---
- name: Setup K3s Cluster
  hosts: all
  become: yes
  tasks:
    - name: Install Master
      shell: curl -sfL https://get.k3s.io | sh -
      when: inventory_hostname in groups['master']
      args: { creates: /usr/local/bin/k3s }

    - name: Get Token from Master
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token
      when: inventory_hostname in groups['master']

    - name: Join Worker to Master
      shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master_node']['ansible_host'] }}:6443 
        K3S_TOKEN={{ hostvars['master_node']['node_token']['stdout'] }} sh -
      when: inventory_hostname in groups['worker']
      args: { creates: /usr/local/bin/k3s-agent }