[master]
master_node ansible_host=13.38.95.162

[worker]
worker_node ansible_host=13.38.217.154

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/yassine/.ssh/the_working_key_v2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

